spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: look1026
    url: jdbc:mysql://localhost:3306/obag?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      use_sql_comments: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

server:
  port: 8082