# Database setup
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/obag?createDatabaseIfNotExist=true
    username: root
    password: "${MYSQL_PASSWORD}" #Envoironment variable
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      use_sql_comments: true
    open-in-view: false

  # HTTP verbs: PUT, DELETE... - hidden methods
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

server:
  port: 8080
  # Error Handling - messages
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never

# CLOUDINARY
cloudinary:
  cloud-name: ivantashev
  api-key: 766423891979133
  api-secret: "${CLOUDINARY_SECRET}"

# ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: beans, caches, health, env, heapdump, threaddump, metrics, scheduledtasks, prometheus


