cloudinary:
    api-key: 766423891979133
    api-secret: ${CLOUDINARY_SECRET}
    cloud-name: ivantashev
management:
    endpoints:
        web:
            exposure:
                include: beans, caches, health, env, heapdump, threaddump, metrics,
                    scheduledtasks, prometheus
server:
    error:
        include-exception: true
        include-message: always
        include-stacktrace: never
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD}
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/obag?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            use_sql_comments: true
        show-sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB
